stages:
    - build
    - deploy-npmjs

variables:
    VERSION: $CI_COMMIT_SHORT_SHA

build:
    stage: build
    image: node:20.10.0
    before_script:
        - npm install -g typescript
        - npm install --dev
    script:
        - npm run build
    artifacts:
        paths:
            - "./dist/"
        expire_in: "1 days"
    only:
        - main

deploy-prod:
    stage: deploy-npmjs
    image: node:20.10.0
    before_script:
        - npm config set //registry.npmjs.org/:_authToken=$NPMJS_TOKEN
    script:
        - npm publish
    only:
        - main